FROM quay.io/keycloak/keycloak:24.0.1
COPY ./keycloak/realm.json /opt/keycloak/data/import/realm.json
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

CMD [ "start-dev", "--import-realm", "--health-enabled=true" ]
