openapi: "3.0.0"
info:
  title: MojeFinance application
  version: 0.0.1

paths:
  /healthcheck:
    get:
      summary: Healthcheck
      operationId: healthcheck
      responses:
        '200':
          description: OK

  /banks:
    get:
      summary: Get connected banks
      operationId: getConnectedBanks
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectedBanksResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products:
    get:
      summary: Get products
      operationId: getProducts
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /banks/connect:
    post:
      summary: Connect to a bank
      operationId: connectBank
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: false
          schema:
            type: string
          description: Authorization code received from financial institution after user authorization (optional)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /banks/disconnect/{client-registration-id}:
    delete:
      summary: Disconnect bank
      operationId: disconnectBank
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: client-registration-id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /registration:
    post:
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPrivate'
      responses:
        '201':
          description: CREATED
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile:
    get:
      summary: Retrieve current user information
      operationId: getCurrentUser
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    Authorization:
      in: header
      name: Authorization
      required: true
      schema:
        type: string

  schemas:
    ConnectedBanksResponse:
      type: object
      properties:
        connectedBanks:
          type: array
          items:
            $ref: '#/components/schemas/Bank'

    ProductsResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'

    Product:
      type: object
      properties:
        productId:
          type: string
        accountName:
          type: string
        bankName:
          type: string
        productIdentification:
          $ref: '#/components/schemas/ProductIdentification'
        currency:
          type: string
        ownersNames:
          type: array
          items:
            type: string
        productCategory:
          type: string
        balance:
          $ref: '#/components/schemas/Balance'
        manuallyCreated:
          type: boolean
        bankCode:
          type: string

    ProductIdentification:
      type: object
      properties:
        iban:
          type: string
        productNumber:
          type: string

    Balance:
      type: object
      properties:
        amount:
          type: number
          format: double
        currency:
          type: string

    Bank:
      type: object
      properties:
        clientRegistrationId:
          type: string
        bankName:
          type: string
        logoUrl:
          type: string
        manuallyCreated:
          type: boolean
        bankConnectionStatus:
          type: string
          enum: [ CONNECTED, DISCONNECTED ]

    ProfileResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserPrivate'

    UserPublic:
      description: Public information about user
      type: object
      properties:
        username:
          type: string

    UserPrivate:
      description: Private information about user
      type: object
      properties:
        userId:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        email:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string