openapi: "3.0.0"
info:
  title: MojeFinance application
  version: 0.0.1

paths:
  /healthcheck:
    get:
      summary: Healthcheck
      operationId: healthcheck
      responses:
        '200':
          description: OK

  /banks:
    get:
      summary: Get connected banks
      operationId: getConnectedBanks
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectedBanksResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products:
    get:
      summary: Get products
      operationId: getProducts
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/assets-liabilities:
    get:
      summary: Get assets and liabilities
      operationId: getAssetsAndLiabilities
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetsAndLiabilitiesResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/cash-flow:
    get:
      summary: Get cash flow summary
      operationId: getCashFlowSummary
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/{clientRegistrationId}/{accountId}/transactions:
    get:
      summary: Get transactions
      operationId: getTransactions
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: clientRegistrationId
          in: path
          required: true
          schema:
            type: string
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /banks/connect:
    post:
      summary: Connect to a bank
      operationId: connectBank
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: false
          schema:
            type: string
          description: Authorization code received from financial institution after user authorization (optional)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /banks/disconnect/{client-registration-id}:
    delete:
      summary: Disconnect bank
      operationId: disconnectBank
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: client-registration-id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /registration:
    post:
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: CREATED
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile:
    get:
      summary: Retrieve current user information
      operationId: getCurrentUser
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    Authorization:
      in: header
      name: Authorization
      required: true
      schema:
        type: string

  schemas:
    ConnectedBanksResponse:
      type: object
      properties:
        connectedBanks:
          type: array
          items:
            $ref: '#/components/schemas/Bank'

    ProductsResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'

    AssetsAndLiabilitiesResponse:
      type: object
      properties:
        assets:
          $ref: '#/components/schemas/AssetLiability'
        liabilities:
          $ref: '#/components/schemas/AssetLiability'

    AssetLiability:
      type: object
      properties:
        groupedProducts:
          type: array
          items:
            $ref: '#/components/schemas/GroupedProducts'
        totalAmount:
          $ref: '#/components/schemas/Amount'

    GroupedProducts:
      type: object
      properties:
        groupName:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        totalAmount:
          $ref: '#/components/schemas/Amount'

    TransactionsResponse:
      type: object
      properties:
        groupedTransactions:
          type: array
          items:
            $ref: '#/components/schemas/GroupedTransactions'

    GroupedTransactions:
      type: object
      properties:
        groupName:
          type: string
        totalIncome:
          $ref: '#/components/schemas/Amount'
        totalExpense:
          $ref: '#/components/schemas/Amount'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        groupedTransactions:
          type: array
          items:
            $ref: '#/components/schemas/GroupedTransactions'

    Transaction:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        direction:
          type: string
          enum: [ INCOME, OUTCOME ]
        status:
          type: string
          enum: [ BOOKED, PENDING ]
        counterpartyName:
          type: string
        category:
          type: string

    Product:
      type: object
      properties:
        productId:
          type: string
        accountName:
          type: string
        bankDetails:
          $ref: '#/components/schemas/BankDetails'
        productIdentification:
          $ref: '#/components/schemas/ProductIdentification'
        currency:
          type: string
        ownersNames:
          type: array
          items:
            type: string
        productCategory:
          type: string
        balance:
          $ref: '#/components/schemas/Amount'
        manuallyCreated:
          type: boolean
        bankCode:
          type: string

    ProductIdentification:
      type: object
      properties:
        iban:
          type: string
        productNumber:
          type: string

    BankDetails:
      type: object
      properties:
        bankName:
          type: string
        clientRegistrationId:
          type: string

    Amount:
      type: object
      properties:
        value:
          type: number
          format: double
        currency:
          type: string

    Bank:
      type: object
      properties:
        clientRegistrationId:
          type: string
        bankName:
          type: string
        logoUrl:
          type: string
        manuallyCreated:
          type: boolean
        bankConnectionStatus:
          type: string
          enum: [ CONNECTED, DISCONNECTED ]

    ProfileResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'

    User:
      description: User information
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        email:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string